# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-04 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emailID', models.EmailField(max_length=254)),
                ('mobileNumber', models.CharField(max_length=10)),
                ('rating', models.CharField(max_length=2)),
                ('review', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
