# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-05 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20190505_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='emailID',
            field=models.CharField(max_length=254),
        ),
    ]
